### PR TITLE
Support protobuf v1.1.0

### LINKED ISSUE #13: Support for golang/protobuf v1.1.0
When trying to build PGS with `golang/protobuf` [v1.1.0](https://github.com/golang/protobuf/releases/tag/v1.1.0) in our vendored deps, it fails:

```
# github.com/chef/a2/vendor/github.com/lyft/protoc-gen-star
vendor/github.com/lyft/protoc-gen-star/gatherer.go:52:33: cannot use f (type *generator.FileDescriptor) as type packageFD in argument to g.PluginBase.Generator.packageName:
        *generator.FileDescriptor does not implement packageFD (missing PackageName method)
vendor/github.com/lyft/protoc-gen-star/gatherer.go:77:5: cannot use f (type *generator.FileDescriptor) as type packageFD in field value:
        *generator.FileDescriptor does not implement packageFD (missing PackageName method)
```

Looks like [`PackageName()` went away here](https://github.com/golang/protobuf/compare/v1.0.0...v1.1.0#diff-8c603013608023320d5242916c4ea03bL102).

### PR DESCRIPTION
**Pull request by rodaine**
Fixes #13 

This is the first pass at supporting v1.1.0 of the protobuf lib. Had to disable/skip some of the tests on account of the lib changing its internal behavior + turn of the parallelism on others to prevent certain races due to use of globals.

Long(est) term solution is to remove the dependency on the lib entirely and just build up the struct and ASTs ourselves. This should address the issues we have now at the very least.

### CODE REVIEW

**Comment by rodaine** [comment]
@srenatus want to give it a test against this branch? Will try it out on some of our internal plugins as well.

**Comment by srenatus** [comment]
@rodaine Will try this on Monday. Thanks for picking this up! 😃

**Comment by srenatus** [comment]
@rodaine Looks good! Had to throw in an override for PGV,
```diff
+[[override]]
+  name = "github.com/lyft/protoc-gen-validate"
+  branch = "master"
+
+[[override]]
+  name = "github.com/lyft/protoc-gen-star"
+  branch = "protobuf-1.1.0"
```
but that's to be expected. Thanks again!

Let's get this merged? 😉 (I haven't looked at the code, no idea if this still works with pb 1.0.0...)

**Comment by rodaine** [comment]
It doesn't work with PB 1.0.0 which is why I made the version in the glide.yaml explicitly >=1.1.0. I wonder if there is a better way to enforce that however.
